apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: devops
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: init-container
            image: busybox:1.28
            command: ["/bin/sh", "-c"]
            args:
             - echo Generate the output file to store the disk details used by filesystem;
               df -T -h > output.txt && sleep 25;
               mv output.txt /cron;
            volumeMounts:
            - name: cron-volume
              mountPath: "/cron"
          containers:
          - name: output-container
            image: busybox:1.28
            command: ["/bin/sh", "-c"]
            args:
             - ls -lart;
               cd cron/ && ls -lart;
               echo Displaying the results of the file that the init container created;
               cat output.txt;
               sleep 25;
            volumeMounts:
            - name: cron-volume
              mountPath: "/cron"
          volumes:
          - name: cron-volume
            emptyDir: {}
          restartPolicy: OnFailure
